### ISSUE TITLE
paxctl requirement error when trying to install using Tumbleweed one click

### ISSUE THREAD

**Issue by zaggynl** [kdave/openSUSE-gardened#3]
Couldn't upload screenshot here so here is an imgur link: https://i.imgur.com/M5jwG8B.png

Did I mess up my repos?

**Comment by kdave** [comment]
No, this is probably an error in dependencies between the packages. I've seen it as well but fixed it. Let me check.

**Comment by kdave** [comment]
Not an error, but the elfix package has been dropped in favor of paxctl. So the resolution is to uninstall elfix in advance, or select 'do not install elfix' in the dialog when updating.
