### ISSUE TITLE
Brightness keys don't work

### ISSUE THREAD

**Issue by anaknaga** [kdave/openSUSE-gardened#4]
Hi, thanks a lot for maintaining this kernel, much appreciated!

I realise redshift not working is probably intended. However, my brightness keys stop working when on your kernel. The visual indicator shows only one 'jump' up and down when I press the buttons. However many times I press the buttons, the indicator is locked in either one of two positions. This doesn't matter however, as the brightness doesn't change regardless, it just doesn't work.

**Comment by kdave** [comment]
Can you please be more specific about the errors? If the redshift works normally but not on grsec kernel, there's some permission or proc/sys/device access required, this could be possibly tuned by paxctl.
The brightness keys might need extra drivers or package, are you using anything any 'kmp' package (ie. kenrnel modules packaged outside of the base package)?

**Comment by anaknaga** [comment]
Sorry for the vagueness. The redshift issue is unrelated. 

The brightness function keys (as well as manual change through terminal) does not work properly on my Thinkpad T450s. When pressing the keys, the notification shows as normal. However, the 'slider' is limited to one jump up and one down. No change in brightness is registered in any case. Drivers for this for my device should be inside the kernel if I'm not mistaken. I'm not running any kernel modules or extra drivers apart from linux-firmware. If you need anything more specific, let me know and I'll check.

**Comment by anaknaga** [comment]
This is the actual error message spit out by journalctl upon pressing the brightness keys:

> Jan 16 10:31:01 T450s-Leap pkexec[25780]: user: Error executing command as another user: Not authorized [USER=root] [TTY=unknown] [CWD=/home/user] [COMMAND=/usr/lib/gnome-settings-daemon-3.0/gsd-backlight-helper --set-brightness 264]

**Comment by kdave** [comment]
The error message comes from sudo, so it could be a permissin/configuation problem. I'd expect a different error this were blocked by grsec functionality.

**Comment by anaknaga** [comment]
Yep, you're right. The testing kernel you built didn't make a difference. I'll look into permissions now, as I suspect this also has to do with me not being able to shut down through gnome (by user), but only by sudo via command line.

**Comment by anaknaga** [comment]
Just to report that setting 'org.gnome.settings-daemon.plugins.power.backlight-helper' in /etc/polkit-1/rules.d/90-default-privs.rules from [ 'no', 'no', 'yes' ] to [ 'yes', 'no', 'yes' ], allows me to change the brightness with the keyboard on the grsec kernel. This file reports it shouldn't be edited though. Also, its original setting doesn't prevent me from setting the brightness with the keyboard on the standard kernel.

**Comment by kdave** [comment]
> I think this relates to the polkit 'known issues' you referenced?

That's quite possible, but I don't recall any specifics. Maybe the other distros with grsec enabled have this already sorted but I haven't seen anything  relevant on a quick skim.

**Comment by anaknaga** [comment]
Fixed both issues by doing this:

`/etc/polkit-default-privs.local
org.gnome.settings-daemon.plugins.power.backlight-helper yes:no:yes
org.freedesktop.login1.power-off-multiple-sessions yes:auth_admin_keep:yes
org.freedesktop.login1.reboot-multiple-sessions yes:auth_admin_keep:yes`
