### ISSUE TITLE
Denied Resource Overstep : RLIMIT_NOFILE

### ISSUE THREAD

**Issue by cicero5150** [kdave/openSUSE-gardened#5]
I keep getting these errors in /var/log/messages

 grsec: denied resource overstep by requesting 2048 for RLIMIT_NOFILE against limit

for numerous programs, including XORG, which I believe is to blame for the random freezes I have been having. I have edited /etc/security/limits.conf to up the limits. However the output for ulimit -n never appears to have any effect. I can't seem to figure out how to make it stick! Thanks.

**Comment by kdave** [comment]
The messages are informational, but maybe too noisy on your system. They are enabled by config option GRKERNSEC_RESLOG (enabled in all kernels), and can be turned off by sysctl `kernel.grsecurity.resource_logging`.
I don't think xorg freezes are related to that, but this would require more debugging to be sure.
I'm not sure if the values from /etc/security/limits.conf are applied as-is or are somehow tuned by PAM, shell or whatever. See what's in /etc/systemd/*.conf in DefaultLimitNOFILE or if any service file does not change it back.

**Comment by cicero5150** [comment]
Thanks for you response and your work bring GRSEC to Opensuse. I'll admit I'm still rather novice at linux and rely on google to troubleshoot issues that arise. My problem is I cannot find information on my system freezes up. Upfront I admit this question is vague, is there anything I should be looking for to hunt down this issue?
My system info;
Display Device : core processor integrated graphics, driver i915
XORG : x-11-server 1.19.1-4.1, video driver 7.6_1-15.2, VESA driver 2.3.4-3.4
I am running tumbleweed, thanks again!
